const DEFAULT_SECRET_STRING_TO_MIX = 'HakunaMatata'
const DEFAULT_MAX_QUESTIONS = 6
const MAX_PROMPT_LENGTH = 4080

export {
  DEFAULT_SECRET_STRING_TO_MIX,
  DEFAULT_MAX_QUESTIONS,
  MAX_PROMPT_LENGTH
}